### ISSUE TITLE
Scroll stops working after 2nd level modal

### ISSUE THREAD

**Issue by donnysim** [impresspages/ImpressPages#691] opened 2015-02-13 14:22 UTC
When you enter a second level modal (upload image from modal or enter form field options modal in form widget) the scrollbar doesn't respond to the modal dialog, but scrolls the webpage instead or doesn't scroll at all. It makes it impossible to scroll down to the save button if the form is long.

**Comment by jankus** [comment] 2015-02-13 14:24
Bootstrap doesn't support multiple modal to be visible at the same time. The correct implementation should close parent modal, open a second one, do what's needed, handle close event and reopen the first one.

In this case you will avoid such bad behavior.

**Comment by HalcyonD** [comment] 2015-02-13 14:26
Then the Form widget and Image uploading from GridController should be updated too :O

**Comment by jankus** [comment] 2015-02-13 14:31
If they act badly then definitely they should be fixed. There are such use cases already in the core.

Form widget works in this way (adding options for radio/checkboxes). Do you see something wrong with it? Or are there some other cases when this behavior breaks?

**Comment by HalcyonD** [comment] 2015-02-13 14:36
I have 47 fields in the form and as soon as I click 'Options' button for any of the fields and close it, it starts to scroll the webpage instead of the insanely long modal :\ IP 4.5.1

**Comment by HalcyonD** [comment] 2015-02-13 14:40
It also stops working in the GridController, as soon as the file select modal opens, select image and it closes, the scroll stops working.

**Comment by maskas** [comment] 2015-02-14 10:47
I can't reproduce anything of that. I probably doning something differently. Could we have a screenshot or so? Are you working on the default or custom theme? Any suspicious plugins?

**Comment by HalcyonD** [comment] 2015-02-14 13:34
Clean IP install, doesn't matter what theme:

[Video](https://www.youtube.com/watch?v=oXlnYCdcQns&feature=youtu.be)

**Comment by maskas** [comment] 2015-02-14 14:28
Ok. Got it now. Thanks.

**Comment by jankus** [comment] 2015-02-17 11:57
I've got the problem. I believe this relates to handling modals - adding/removing global classes, etc. New Bootstrap has a different implementation for modal backdrop compared to previous versions. JavaScript adds/removes CSS classes from the body tag. Maybe that's the case.

**Comment by HalcyonD** [comment] 2015-02-17 14:13
Seems like the case, after you close 2nd modal dialog, it removes the `.modal-open` class from body. If you put it back manually, the scroll works again.

**Closed** 2023-10-11 05:41 UTC
Labels: Bug, 4.x
