### ISSUE TITLE
Bug - update url's

### ISSUE THREAD

**Issue by rzusto** [impresspages/ImpressPages#737] opened 2015-07-14 20:33 UTC
In latest version 4.6.2, Impresspages have a bug.
The problem concerns the update URL's. Because I am not a programmer - I publish the video and the screenshots that show what the problem is.

![zrzut ekranu 2015-07-14 o 21 54 33](https://cloud.githubusercontent.com/assets/8398481/8683777/f594066c-2a74-11e5-913a-de079cceed55.png)
![zrzut ekranu 2015-07-14 o 21 54 57](https://cloud.githubusercontent.com/assets/8398481/8683778/f59698a0-2a74-11e5-8fa5-27b7e03730e3.png)
https://www.youtube.com/watch?v=x8ryLAWzAwY&feature=youtu.be

**Comment by maskas** [comment] 2015-07-15 17:19
That's a finding :O

**Comment by maskas** [comment] 2015-07-19 11:03
I can't reproduce. That basically means that this is related to the actual data in your database. Unfortunately Ip/Internal/Content/Model.php:687 doesn't look like the one that could throw such an error. Could you please tell me which ImpressPages version are you using?

**Comment by TheFOBas** [comment] 2015-07-19 12:07
I was able to reproduce this and my last commit was made to fix this.  https://github.com/impresspages/ImpressPages/commit/dbe16e24c329f6a775b32dc5fba3c9cdc385f50f

**Comment by rzusto** [comment] 2015-07-19 13:25
I use 4.6.3 version. I think there wasn't such a problem earlier. I checked TheFOBas commit - He solved this problem.

**Comment by maskas** [comment] 2015-07-20 17:15
Cool. As far as I remember that commit is merged into master so will be included in next release.

**Closed by maskas** 2015-07-20 17:15 UTC
