### ISSUE TITLE
Unable to enter location for a google map

### ISSUE THREAD

**Issue by santo74** [impresspages/ImpressPages#664] opened 2015-01-11 19:53 UTC
When I drag a map widget into a block on my page, I see no way to enter a location for that map.
According to the [docs of the maps widget](https://github.com/impresspages-plugins/2.x_map), I should do the following:
```
    Drag the widget from administration toolbar to desirable block on your page.
    Search for desired location.
    Click Confirm button.
```
But I don't see a way to do the search and/or enter the desired location directly nor do I see a confirm button.

The only thing I can do is zoom in on the map until I reach the desired location, but this is a cumbersome process and I can't imagine that's the way it's supposed to be working.

**Comment by maskas** [comment] 2015-01-11 20:08
That text may be a bit missleading. Search in that case meant to be browsing the map. 

So basically this ticket is a duplicate of https://github.com/impresspages/ImpressPages/issues/446

**Closed by maskas** 2015-01-11 20:08 UTC

**Comment by santo74** [comment] 2015-01-11 20:16
Ok, thanks for the clarification.
